services:
  php:
    image: php:8.2-fpm
    container_name: lab4_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    # Добавляем необходимые PHP расширения
    command: >
      sh -c "
      docker-php-ext-install mysqli pdo pdo_mysql &&
      docker-php-ext-enable mysqli pdo_mysql &&
      php-fpm
      "

  web:
    image: nginx:alpine
    container_name: lab4_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php